Feature authentication
StelianRBG/ELSYS-GIS-iOS pull request #1
Opened 2022-01-27 08:47 UTC by StelianRBG

Make a screens for Login, Registration, Authentication, Home, Marks, User setings, Create Mark, Show Mark information.

Add working registration and login with email and password. (Store user data as: uid, email, username  in Firestore)

2022-01-28 13:45 UTC, Lubakis commented
Липсва файл .gitignore. Потърси един добави го и махни ненужните файлове от GIT

2022-02-14 18:07 UTC, Lubakis requested changes
Адресирай първо промените тук и после прави други неща :)

2022-02-14 18:07 UTC, Lubakis commented on MarkMe/MarkMe/AppDelegate.swift
> +        FirebaseApp.configure()
Виж дали е не по-добре да се случва на applicationDidBecomeActive

2022-02-14 18:07 UTC, Lubakis commented on MarkMe/MarkMe/Extensions.swift
> +        let alert = UIAlertController(title: "Errror", message: alertMessage, preferredStyle: .alert)
Заглавието е грешно. Хубаво е да подаваш и заглавието като параметър най-вероятно.

2022-02-14 18:07 UTC, Lubakis commented on MarkMe/MarkMe/View Controllers/CreateMarkVC.swift
> +        button.layer.borderColor = UIColor.black.cgColor
На няколко места ползваш бутони със закръгляния и конфигурация. Може би не е лошо да си направиш наследник на бутон. Да дефинираш 2-3 вида бутона и да ги конфигурариш чрез някакво състояние. Пиша само този коментар за всички места. Другите ще са с референция "бутони".

2022-02-14 18:07 UTC, Lubakis commented on MarkMe/MarkMe/View Controllers/HomeVC.swift
> +        addButton.layer.cornerRadius = addButton.frame.width / 2
Бутони

2022-02-14 18:07 UTC, Lubakis commented on MarkMe/MarkMe/View Controllers/LoginVC.swift
>              button.layer.borderWidth = 2
Бутони

2022-02-14 18:07 UTC, Lubakis commented on MarkMe/MarkMe/View Controllers/LoginVC.swift
> +    @IBOutlet weak var usernameField: UITextField!
Оутлетите няма нужда да бъдат weak, но има нужда да бъдат private.

2022-02-14 18:07 UTC, Lubakis commented on MarkMe/MarkMe/View Controllers/LoginVC.swift
> +            db.collection("User").whereField("username", isEqualTo: username).getDocuments() { (querySnapshot, err) in
Правиш strong capture на self. Това не е добре. Във всички callbacks е хубаво да имаш [weak self] и после да го достъпваш като optional self?

2022-02-14 18:07 UTC, Lubakis commented on MarkMe/MarkMe/View Controllers/LoginVC.swift
> +            let username = usernameField.text!
Без force unwrap!

2022-02-14 18:07 UTC, Lubakis commented on MarkMe/MarkMe/View Controllers/LoginVC.swift
> +            let db = Firestore.firestore()
Може би е по-добре базата данни да бъде достъпена веднъж още при иницализация на класа.

2022-02-14 18:07 UTC, Lubakis commented on MarkMe/MarkMe/View Controllers/LoginVC.swift
> +                    print("Error getting documents: \(err)")
Защо не показваме смислена грешка?

2022-02-14 18:07 UTC, Lubakis commented on MarkMe/MarkMe/View Controllers/LoginVC.swift
> +                        self.showAlert(alertMessage: "User is not found!")
Отбележи си // TODO когато не съществува потребител предложи регистрация с въведения email или отказ.

2022-02-14 18:07 UTC, Lubakis commented on MarkMe/MarkMe/View Controllers/LoginVC.swift
> +                        print(type(of: email))
Това е код за дебъгване. Няма място в сорс контрол системата.

2022-02-14 18:07 UTC, Lubakis commented on MarkMe/MarkMe/View Controllers/RegisterVC.swift
> +    @IBOutlet weak var usernameField: UITextField!
Нека бъдат частни (private) и нека не бъдат strong референции

2022-02-14 18:07 UTC, Lubakis commented on MarkMe/MarkMe/View Controllers/RegisterVC.swift
> +            if err != nil {
По-добре е да направиш `guard err == nil else { ... return } `

2022-02-14 18:07 UTC, Lubakis commented on MarkMe/MarkMe/View Controllers/RegisterVC.swift
> +            let username = usernameField.text!
Без !

2022-02-14 18:07 UTC, Lubakis commented on MarkMe/MarkMe/View Controllers/RegisterVC.swift
> +        if usernameField.text?.isEmpty ?? true || emailField.text?.isEmpty ?? true || passwordField.text?.isEmpty ?? true || confirmPassField.text?.isEmpty ?? true {
Можеш да направиш guard, с което ще намалиш дълбочината на кода

2022-02-14 18:07 UTC, Lubakis commented on MarkMe/MarkMe/View Controllers/RegisterVC.swift
> +            if password.count < 8 {
Валидацията може да бъде в отделна функция. Нека се опитаме да няма функции по-дълги от 25-30 реда освен ако не е напълно задължително

2022-02-14 18:07 UTC, Lubakis commented on MarkMe/MarkMe/View Controllers/UserVC.swift
> +        // Do any additional setup after loading the view.
Ненужен остатъчен коментар

2022-02-14 18:07 UTC, Lubakis commented on MarkMe/MarkMe/View Controllers/UserVC.swift
> +            button.layer.borderColor = UIColor.black.cgColor
Бутон от тип вместо цикъл с бутони, които да конфигурираме

2022-02-14 18:07 UTC, Lubakis commented on MarkMe/MarkMe/View Controllers/UserVC.swift
> +            try Auth.auth().signOut()
Това не е ли асинхронно?

2022-02-14 18:07 UTC, Lubakis commented on MarkMe/MarkMe/Extensions.swift
> +    func toHash() -> String {
Това ползва ли се?

2022-02-14 18:39 UTC, StelianRBG commented on MarkMe/MarkMe/View Controllers/UserVC.swift
> +            try Auth.auth().signOut()
не

2022-02-14 20:45 UTC, StelianRBG commented on MarkMe/MarkMe/View Controllers/RegisterVC.swift
> +    @IBOutlet weak var usernameField: UITextField!
не дава да бъдат strong - връща гршка

2022-02-14 22:20 UTC, StelianRBG commented on MarkMe/MarkMe/View Controllers/LoginVC.swift
> +                    print("Error getting documents: \(err)")
Защото не ми хрумва какво да връщам и затова връщам гршката която получавам от Firebase

2022-02-16 13:05 UTC, Lubakis commented on MarkMe/MarkMe/View Controllers/LoginVC.swift
> +                    print("Error getting documents: \(err)")
Това не е ли грешка, че няма такъв потребител?

2022-02-16 14:35 UTC, Lubakis commented on MarkMe/MarkMe/Style Models/RoundedButtonModel.swift
> +class RoundedButtonModel: UIButton {
Защо се казва модел? Това е просто RoundedButton. Модел е обект, който съдържа само данни най-често от простите типове.

2022-02-16 14:35 UTC, Lubakis commented on MarkMe/MarkMe/Style Models/TextFieldModel.swift
> +class TextFieldModel: UITextField {
Защо се казва модел? Това е просто TextField или нещо, което включва TextField накрая. Модел е обект, който съдържа само данни най-често от простите типове.

2022-02-16 14:35 UTC, Lubakis commented on MarkMe/MarkMe/View Controllers/HomeVC.swift
> +        addButton.layer.cornerRadius = addButton.frame.width / 2
Няма ли някои бутон, който да поддържа заоблени ъгли и бордър?

2022-02-16 14:35 UTC, Lubakis commented on MarkMe/MarkMe/View Controllers/LoginVC.swift
> +        guard (username.isEmpty || password.isEmpty ) == false else {
По-правилна структура на този код е:
`guard !username.isEmpty, !password.isEmpty`

2022-02-16 14:35 UTC, Lubakis commented on MarkMe/MarkMe/View Controllers/LoginVC.swift
> +        guard (username.isEmpty || password.isEmpty ) == false else {
Тези трите могат да се случат в общ guard

2022-02-16 14:36 UTC, StelianRBG commented on MarkMe/MarkMe/Extensions.swift
> +        let alert = UIAlertController(title: "Errror", message: alertMessage, preferredStyle: .alert)
Оправено

2022-02-16 14:36 UTC, StelianRBG commented on MarkMe/MarkMe/View Controllers/CreateMarkVC.swift
> +        button.layer.borderColor = UIColor.black.cgColor
Оправено

2022-02-16 14:36 UTC, StelianRBG commented on MarkMe/MarkMe/View Controllers/HomeVC.swift
> +        addButton.layer.cornerRadius = addButton.frame.width / 2
Оправено

2022-02-16 14:36 UTC, StelianRBG commented on MarkMe/MarkMe/View Controllers/LoginVC.swift
>              button.layer.borderWidth = 2
Оправено

2022-02-16 14:36 UTC, StelianRBG commented on MarkMe/MarkMe/View Controllers/LoginVC.swift
> +    @IBOutlet weak var usernameField: UITextField!
Оправено

2022-02-16 14:36 UTC, StelianRBG commented on MarkMe/MarkMe/View Controllers/LoginVC.swift
> +            db.collection("User").whereField("username", isEqualTo: username).getDocuments() { (querySnapshot, err) in
Оправено

2022-02-16 14:36 UTC, StelianRBG commented on MarkMe/MarkMe/View Controllers/LoginVC.swift
> +            let username = usernameField.text!
Оправено

2022-02-16 14:36 UTC, StelianRBG commented on MarkMe/MarkMe/View Controllers/LoginVC.swift
> +            let db = Firestore.firestore()
Оправено

2022-02-16 14:37 UTC, StelianRBG commented on MarkMe/MarkMe/View Controllers/LoginVC.swift
> +                    print("Error getting documents: \(err)")
Оправено

2022-02-16 14:37 UTC, StelianRBG commented on MarkMe/MarkMe/View Controllers/LoginVC.swift
> +                        print(type(of: email))
Оправено

2022-02-16 14:37 UTC, stodorichkov commented on MarkMe/MarkMe/View Controllers/RegisterVC.swift
> +    @IBOutlet weak var usernameField: UITextField!
Оправено

2022-02-16 14:38 UTC, StelianRBG commented on MarkMe/MarkMe/View Controllers/RegisterVC.swift
> +            if err != nil {
Оправено

2022-02-16 14:38 UTC, StelianRBG commented on MarkMe/MarkMe/View Controllers/RegisterVC.swift
> +            let username = usernameField.text!
Оправено

2022-02-16 14:38 UTC, StelianRBG commented on MarkMe/MarkMe/View Controllers/RegisterVC.swift
> +        if usernameField.text?.isEmpty ?? true || emailField.text?.isEmpty ?? true || passwordField.text?.isEmpty ?? true || confirmPassField.text?.isEmpty ?? true {
Оправено

2022-02-16 14:38 UTC, StelianRBG commented on MarkMe/MarkMe/View Controllers/RegisterVC.swift
> +            if password.count < 8 {
Оправено

2022-02-16 14:38 UTC, StelianRBG commented on MarkMe/MarkMe/View Controllers/UserVC.swift
> +        // Do any additional setup after loading the view.
Оправено

2022-02-16 14:38 UTC, StelianRBG commented on MarkMe/MarkMe/View Controllers/UserVC.swift
> +            button.layer.borderColor = UIColor.black.cgColor
Оправено

2022-02-16 14:39 UTC, StelianRBG commented on MarkMe/MarkMe/Extensions.swift
> +    func toHash() -> String {
Оправено

2022-02-16 14:41 UTC, StelianRBG commented on MarkMe/MarkMe/Style Models/RoundedButtonModel.swift
> +class RoundedButtonModel: UIButton {
тогава групата в която са да я прекръстя ли

2022-02-16 15:07 UTC, StelianRBG commented on MarkMe/MarkMe/View Controllers/LoginVC.swift
> +        guard (username.isEmpty || password.isEmpty ) == false else {
Оправено

2022-02-16 15:08 UTC, StelianRBG commented on MarkMe/MarkMe/View Controllers/LoginVC.swift
> +        guard (username.isEmpty || password.isEmpty ) == false else {
Оправено

2022-02-16 15:26 UTC, StelianRBG commented on MarkMe/MarkMe/Style Models/TextFieldModel.swift
> +class TextFieldModel: UITextField {
Оправено

2022-02-16 15:38 UTC, StelianRBG commented on MarkMe/MarkMe/Style Models/RoundedButtonModel.swift
> +class RoundedButtonModel: UIButton {
Оправено

2022-02-16 15:41 UTC, Lubakis approved these changes

2022-02-16 15:53 UTC, merged