Feature create mark
StelianRBG/ELSYS-GIS-iOS pull request #4
Opened 2022-02-28 19:49 UTC by StelianRBG

2022-03-08 08:37 UTC, Lubakis requested changes
Има доста неща за оправяне. Някои сме ги говорили вече. Ако имаш въпроси да се чуем

2022-03-08 08:37 UTC, Lubakis commented on MarkMe/MarkMe/Model/Mark.swift
> +    @DocumentID var id: String? = UUID().uuidString
Защо е optional?

2022-03-08 08:37 UTC, Lubakis commented on MarkMe/MarkMe/Screens/CreateMarks/CreateMarkViewController.swift
> +import SwiftUI
За какво ползваш SwiftUI?

2022-03-08 08:37 UTC, Lubakis commented on MarkMe/MarkMe/Screens/CreateMarks/CreateMarkViewController.swift
> +    @IBOutlet weak var descriptionField: TextView!
Защо някои outlets са private, други weak? Как решаваш?

2022-03-08 08:37 UTC, Lubakis commented on MarkMe/MarkMe/Screens/CreateMarks/CreateMarkViewController.swift
> +    var pickerView = UIPickerView()
Сигурен ли си, че всичко това трябва да е публично?

2022-03-08 08:37 UTC, Lubakis commented on MarkMe/MarkMe/Screens/CreateMarks/CreateMarkViewController.swift
> +        setupLocationMenager()
Правописна грешка - "Manager"  е думата.

2022-03-08 08:37 UTC, Lubakis commented on MarkMe/MarkMe/Screens/CreateMarks/CreateMarkViewController.swift
> +    let locationMenager = CLLocationManager()
Правописна грешка - "Manager"  е думата.

2022-03-08 08:37 UTC, Lubakis commented on MarkMe/MarkMe/Screens/CreateMarks/CreateMarkViewController.swift
> +        return markTypes.count
Не можем ли да взимаме тези данни директно от viewModel вместо да ги пазим във ViewController?

2022-03-08 08:37 UTC, Lubakis commented on MarkMe/MarkMe/Screens/CreateMarks/CreateMarkViewController.swift
> +        return markTypes[row].type
Не можем ли да взимаме тези данни директно от viewModel вместо да ги пазим във ViewController?

2022-03-08 08:37 UTC, Lubakis commented on MarkMe/MarkMe/Screens/CreateMarks/CreateMarkViewController.swift
> +        typeTextField.text = markTypes[row].type
Не можем ли да взимаме тези данни директно от viewModel вместо да ги пазим във ViewController?

2022-03-08 08:37 UTC, Lubakis commented on MarkMe/MarkMe/Screens/CreateMarks/CreateMarkViewModel.swift
> +import UIKit
Защо е нужен UIKit?

2022-03-08 08:37 UTC, Lubakis commented on MarkMe/MarkMe/Screens/CreateMarks/CreateMarkViewModel.swift
> +                    guard let markType = try document.data(as: MarkType.self) else{
Празно място след else липсва

2022-03-08 08:37 UTC, Lubakis commented on MarkMe/MarkMe/Screens/CreateMarks/CreateMarkViewModel.swift
> +                }
Можеш да пробваш да потърсиш Higher-Order Functions и да позлваш някоя от тях за да направиш кода по-четим (map, filter, reduce)

2022-03-08 08:37 UTC, Lubakis commented on MarkMe/MarkMe/Screens/CreateMarks/CreateMarkViewModel.swift
> +                return
Тук не трябва ли да извикаш completion с някаква грешка?

2022-03-08 08:37 UTC, Lubakis commented on MarkMe/MarkMe/Screens/CreateMarks/CreateMarkViewModel.swift
> +            return .failure(AlertError(title: "Validation Error", message: "The form must be completed!"))
Виждам, че на доста места ползваш Strings, които се повтарят. По-удачно е да направиш enum, който да бъде вида грешка - Validation, Address, Database и други и да имаш различни съобщения за различните грешки. Може да се направи с enum с associated values.

2022-03-08 08:37 UTC, Lubakis commented on MarkMe/MarkMe/Screens/CreateMarks/CreateMarkViewModel.swift
> +            return .failure(AlertError(title: "Database Erroe", message: error.localizedDescription))
Печатна грешка заради това, че се повтаря на много места вместо да направиш един Enum

2022-03-08 08:37 UTC, Lubakis commented on MarkMe/MarkMe/Screens/CreateMarks/CreateMarkViewModel.swift
> +        let vaidationResult = validateData(title: title, description: description, type: type, location: location)
Тази функция може директно да връща optional Марк. Можеш да използваш  guard и ако Mark съществува да продължиш надолу. В противен случай да върнеш грешка.

2022-03-08 08:37 UTC, Lubakis commented on MarkMe/MarkMe/Screens/CreateMarks/CreateMarkViewModel.swift
> +                    return
Мисля, че трябва да върнеш някаква грешка тук

2022-03-08 08:37 UTC, Lubakis commented on MarkMe/MarkMe/Screens/CreateMarks/CreateMarkViewModel.swift
> +    func createMark(title: String?,description: String?, type: String?, location: CLLocationCoordinate2D, image: UIImage?, completion: @escaping (Result<Void, AlertError>)->()) {
Тази функция е 100 реда. Хубаво е да се разбие на по-малки. Не по-големи от 30-40 реда.

2022-03-08 08:37 UTC, Lubakis commented on MarkMe/MarkMe/Screens/Home/HomeViewController.swift
> +           let region = MKCoordinateRegion.init(center: location, latitudinalMeters: 1000, longitudinalMeters: 1000)
Хубаво е това 1000 да стане някаква константа в класа и да има някакво име

2022-03-08 08:37 UTC, Lubakis commented on MarkMe/MarkMe/Screens/Home/HomeViewController.swift
> +            let alert = UIAlertController(title: "Access to location denied", message: "Allow acces to the location services!", preferredStyle: .alert)
Този код се повтаря. Може да се обособи във функция

2022-03-08 08:37 UTC, Lubakis commented on MarkMe/MarkMe/Screens/Login/LoginRouter.swift
> +class LoginRouter: Router {
Рутерите ти в момента са повтараящи се класове. В рутера трябва да имаш дефиниция на функция, която да те заведе на точно конкретно място, а не да ѝ подаваш къде да отидеш.

2022-03-08 08:37 UTC, Lubakis commented on MarkMe/MarkMe/Screens/Login/LoginViewController.swift
> +            router.goToNextScreen(storyboardName: screen.storyboardName, storyboardId: screen.storyboardId)
Тук трябва да можеш да викнеш функция, която директно да те прати, където очакваш да отидеш, а рутера да знае как да отиде там.

2022-03-08 08:37 UTC, Lubakis commented on MarkMe/MarkMe/Screens/Login/LoginViewModel.swift
> +                return
Тук трявба да има грешка

2022-03-08 08:37 UTC, Lubakis commented on MarkMe/MarkMe/Screens/Login/LoginViewModel.swift
> +                return
Тук трябва да има грешка

2022-03-08 08:37 UTC, Lubakis commented on MarkMe/MarkMe/Screens/Login/LoginRouter.swift
> +    func goToNextScreen(storyboardName: String, storyboardId: String) {
Тази функция трябва да води на точно конкретно място винаги.

2022-03-08 08:37 UTC, Lubakis commented on MarkMe/MarkMe/Screens/Main/MainRouter.swift
> +    func goToNextScreen(storyboardName: String, storyboardId: String) {
Тази функция трябва да води на точно конкретно място винаги

2022-03-08 08:37 UTC, Lubakis commented on MarkMe/MarkMe/Screens/Main/MainViewModel.swift
> +//        Timer.scheduledTimer(withTimeInterval: 0.5, repeats: false, block: { (timer) in
Коментарите са ненужни

2022-03-08 08:37 UTC, Lubakis commented on MarkMe/MarkMe/Screens/Registration/RegistrationRouter.swift
> +    func goToNextScreen(storyboardName: String, storyboardId: String) {
Същото като при другите рутери

2022-03-08 08:37 UTC, Lubakis commented on MarkMe/MarkMe/Screens/Registration/RegistrationViewModel.swift
> +        let vaidationResult = validateData(usernameField: usernameField, emailField: emailField, passwordField: passwordField, confirmPassField: confirmPassField)
Тук може да имаш Optional, който да се връща и намалиш следващите редове.

2022-03-08 08:37 UTC, Lubakis commented on MarkMe/MarkMe/Screens/Registration/RegistrationViewModel.swift
> +            }
Много дълбока вложеност и не всички грешки се връщат

2022-03-08 08:37 UTC, Lubakis commented on MarkMe/MarkMe/Screens/Registration/RegistrationViewModel.swift
> +            return .failure(AlertError(title: "Validation Error", message: "Password not confirmed"))
Добър пример за нуждата на Enum в грешките

2022-03-08 08:37 UTC, Lubakis commented on MarkMe/MarkMe/Screens/User/UserRouter.swift
> +    func goToNextScreen(storyboardName: String, storyboardId: String) {
Помисли пак за рутерите. Ако не се сещаш - питай

2022-03-08 08:37 UTC, Lubakis commented on MarkMe/MarkMe/Screens/User/UserViewController.swift
> +    @IBOutlet weak var userLabel: UILabel!
Защо е weak?

2022-03-08 08:37 UTC, Lubakis commented on MarkMe/MarkMe/Screens/CreateMarks/CreateMarkViewModel.swift
> +                            return
Липсва грешка

2022-03-08 08:37 UTC, Lubakis commented on MarkMe/MarkMe/Screens/CreateMarks/CreateMarkViewModel.swift
> +                        let dbResult = self?.addMark(mark: newMark)
Това може просто да връща Optional и да създаваш грешка тук

2022-03-08 15:56 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/CreateMarks/CreateMarkViewController.swift
> +import SwiftUI
оправено

2022-03-08 15:57 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/CreateMarks/CreateMarkViewController.swift
> +    @IBOutlet weak var descriptionField: TextView!
Оправено

2022-03-08 16:00 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/CreateMarks/CreateMarkViewController.swift
> +    var pickerView = UIPickerView()
Оправено

2022-03-08 16:01 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/CreateMarks/CreateMarkViewController.swift
> +        setupLocationMenager()
Оправено

2022-03-08 16:01 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/CreateMarks/CreateMarkViewController.swift
> +    let locationMenager = CLLocationManager()
Оправено

2022-03-08 16:03 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/CreateMarks/CreateMarkViewModel.swift
> +import UIKit
защото func createMark приема UIImage

2022-03-08 16:20 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/CreateMarks/CreateMarkViewController.swift
> +    let locationMenager = CLLocationManager()
Оправено

2022-03-08 16:36 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/CreateMarks/CreateMarkViewController.swift
> +        return markTypes.count
Оправено

2022-03-08 16:36 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/CreateMarks/CreateMarkViewController.swift
> +        return markTypes[row].type
Оправено

2022-03-08 16:36 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/CreateMarks/CreateMarkViewController.swift
> +        typeTextField.text = markTypes[row].type
Оправено

2022-03-08 16:38 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/CreateMarks/CreateMarkViewModel.swift
> +                    guard let markType = try document.data(as: MarkType.self) else{
Оправено

2022-03-08 16:38 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/CreateMarks/CreateMarkViewModel.swift
> +                }
Оправено

2022-03-08 16:43 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/CreateMarks/CreateMarkViewModel.swift
> +import UIKit
Оправено

2022-03-08 17:00 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/CreateMarks/CreateMarkViewModel.swift
> +            return .failure(AlertError(title: "Validation Error", message: "The form must be completed!"))
Оправено

2022-03-08 17:00 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/CreateMarks/CreateMarkViewModel.swift
> +            return .failure(AlertError(title: "Database Erroe", message: error.localizedDescription))
Оправено

2022-03-08 17:13 UTC, stodorichkov commented on MarkMe/MarkMe/Screens/CreateMarks/CreateMarkViewModel.swift
> +                return
Оправено

2022-03-08 17:27 UTC, stodorichkov commented on MarkMe/MarkMe/Screens/CreateMarks/CreateMarkViewModel.swift
> +        let vaidationResult = validateData(title: title, description: description, type: type, location: location)
Оправено

2022-03-08 17:29 UTC, stodorichkov commented on MarkMe/MarkMe/Screens/Main/MainViewModel.swift
> +//        Timer.scheduledTimer(withTimeInterval: 0.5, repeats: false, block: { (timer) in
Оправено

2022-03-08 17:32 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/CreateMarks/CreateMarkViewModel.swift
> +                    return
Оправено

2022-03-08 18:21 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/CreateMarks/CreateMarkViewModel.swift
> +    func createMark(title: String?,description: String?, type: String?, location: CLLocationCoordinate2D, image: UIImage?, completion: @escaping (Result<Void, AlertError>)->()) {
Оправено

2022-03-08 18:27 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/Registration/RegistrationViewModel.swift
> +            return .failure(AlertError(title: "Validation Error", message: "Password not confirmed"))
Оправено

2022-03-08 18:31 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/Home/HomeViewController.swift
> +           let region = MKCoordinateRegion.init(center: location, latitudinalMeters: 1000, longitudinalMeters: 1000)
Оправено

2022-03-08 18:38 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/Home/HomeViewController.swift
> +            let alert = UIAlertController(title: "Access to location denied", message: "Allow acces to the location services!", preferredStyle: .alert)
Оправено

2022-03-08 19:15 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/Login/LoginRouter.swift
> +class LoginRouter: Router {
регистрирайте потребител

2022-03-08 19:15 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/Login/LoginRouter.swift
> +class LoginRouter: Router {
Оправено

2022-03-08 19:16 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/Login/LoginViewController.swift
> +            router.goToNextScreen(storyboardName: screen.storyboardName, storyboardId: screen.storyboardId)
Оправено

2022-03-08 19:18 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/Login/LoginRouter.swift
> +    func goToNextScreen(storyboardName: String, storyboardId: String) {
Оправено

2022-03-08 19:18 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/Main/MainRouter.swift
> +    func goToNextScreen(storyboardName: String, storyboardId: String) {
Оправено

2022-03-08 19:18 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/Registration/RegistrationRouter.swift
> +    func goToNextScreen(storyboardName: String, storyboardId: String) {
Оправено

2022-03-08 19:19 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/User/UserRouter.swift
> +    func goToNextScreen(storyboardName: String, storyboardId: String) {
Оправено

2022-03-08 19:20 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/User/UserViewController.swift
> +    @IBOutlet weak var userLabel: UILabel!
Оправено

2022-03-08 19:22 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/Login/LoginViewModel.swift
> +                return
Не трябва това е проверка, когато е кликнат cancell бутона на FB да затвори прозореца.

2022-03-08 19:24 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/Login/LoginViewModel.swift
> +                return
Оправено

2022-03-08 19:28 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/Main/MainRouter.swift
> +    func goToNextScreen(storyboardName: String, storyboardId: String) {
Оправено

2022-03-08 19:29 UTC, StelianRBG commented on MarkMe/MarkMe/Model/Mark.swift
> +    @DocumentID var id: String? = UUID().uuidString
Оправено

2022-03-08 21:39 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/CreateMarks/CreateMarkViewModel.swift
> +                        let dbResult = self?.addMark(mark: newMark)
Оправено

2022-03-09 15:28 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/CreateMarks/CreateMarkViewModel.swift
> +                            return
Оправено

2022-03-09 17:03 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/Registration/RegistrationViewModel.swift
> +            }
Оправено

2022-03-10 08:49 UTC, Lubakis requested changes
Още малко и сме там

2022-03-10 08:49 UTC, Lubakis commented on MarkMe/MarkMe/Model/AlertError.swift
> +    case facebook = "Facebook Error"
Имах предвид това: https://www.swiftbysundell.com/basics/error-handling/

Разгледай

2022-03-10 08:49 UTC, Lubakis commented on MarkMe/MarkMe/Model/AlertError.swift
> +}
Разгледай това: https://www.swiftbysundell.com/basics/error-handling/

2022-03-10 08:49 UTC, Lubakis commented on MarkMe/MarkMe/Model/User.swift
> +    }
Можеш да направиш designated initialiser който да взима username и password и convenience initialiser, който да взима и email, но да вика designated initialiser-a

2022-03-10 08:49 UTC, Lubakis commented on MarkMe/MarkMe/Model/User.swift
> +    enum CodingKeys: String, CodingKey {
Защо ти се налага да кодираш този обект?

2022-03-10 08:49 UTC, Lubakis commented on MarkMe/MarkMe/Screens/CreateMarks/CreateMarkViewModel.swift
>      let geoCodder = CLGeocoder()
Тези трябва ли да са публични?

2022-03-10 08:49 UTC, Lubakis commented on MarkMe/MarkMe/Screens/CreateMarks/CreateMarkViewModel.swift
> +    var creator = ""
Това не трябва ли да потребител?

2022-03-10 08:49 UTC, Lubakis commented on MarkMe/MarkMe/Screens/Home/HomeViewController.swift
> +    let regionMeters: Double = 1000
private най-вероятно?

2022-03-10 08:49 UTC, Lubakis commented on MarkMe/MarkMe/Screens/Home/HomeViewController.swift
>              let alert = UIAlertController(title: "", message: "Turn on Location Services to Allow 'MarkMe' to Determine Your Location", preferredStyle: .alert)
Можеше да направиш директно функция, в която да подаваш двата string-а

2022-03-10 08:49 UTC, Lubakis commented on MarkMe/MarkMe/Screens/Home/HomeViewController.swift
> +            showSettingsAlert(alert: alert)
По-добре е да подадеш текста, а не UIAlertController

2022-03-10 08:49 UTC, Lubakis commented on MarkMe/MarkMe/Screens/Home/HomeViewController.swift
> +        router.goToCreateMark()    }
Кодът не е форматиран правилно

2022-03-10 08:49 UTC, Lubakis commented on MarkMe/MarkMe/Screens/Main/MainRouter.swift
> +    func goTo(target: UIViewController) {
Струва ми се, че тази функция се повтаря на много места. Дали не е удачно да е част от самия Router?

2022-03-10 08:49 UTC, Lubakis commented on MarkMe/MarkMe/Screens/Main/ViewController.swift
> +            switch result {
В този случай е по-добре да използваш if else

2022-03-10 08:57 UTC, Lubakis commented on MarkMe/MarkMe/Screens/Login/LoginViewModel.swift
> +                return
А твоят код как ще разбере, че си затворил прозореца, когато извикаш loginWithFacebook?

2022-03-10 08:57 UTC, Lubakis commented on MarkMe/MarkMe/Screens/Registration/RegistrationViewModel.swift
> +        let vaidationResult = validateData(usernameField: usernameField, emailField: emailField, passwordField: passwordField, confirmPassField: confirmPassField)
Това не си го видял ли?

2022-03-10 09:23 UTC, StelianRBG commented on MarkMe/MarkMe/Model/User.swift
> +    enum CodingKeys: String, CodingKey {
Защото не искам да запазвам в базата паролата на потребителя

2022-03-10 09:29 UTC, StelianRBG commented on MarkMe/MarkMe/Model/User.swift
> +    }
Оправено

2022-03-10 09:30 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/CreateMarks/CreateMarkViewModel.swift
> +    var creator = ""
Не, защото creator може да бъде и потребител, който е влязал с provider различен от email, а тези потребтели не ги пазя в базата данни.

2022-03-10 09:33 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/CreateMarks/CreateMarkViewModel.swift
>      let geoCodder = CLGeocoder()
Оправено

2022-03-10 09:35 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/Home/HomeViewController.swift
> +    let regionMeters: Double = 1000
Оправено

2022-03-10 09:37 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/Main/ViewController.swift
> +            switch result {
Оправено

2022-03-10 09:45 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/Main/MainRouter.swift
> +    func goTo(target: UIViewController) {
Оправено

2022-03-10 09:46 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/Home/HomeViewController.swift
> +        router.goToCreateMark()    }
Оправено

2022-03-10 09:49 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/Home/HomeViewController.swift
> +            showSettingsAlert(alert: alert)
Оправено

2022-03-10 10:20 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/Home/HomeViewController.swift
>              let alert = UIAlertController(title: "", message: "Turn on Location Services to Allow 'MarkMe' to Determine Your Location", preferredStyle: .alert)
Оправено

2022-03-10 10:32 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/Registration/RegistrationViewModel.swift
> +        let vaidationResult = validateData(usernameField: usernameField, emailField: emailField, passwordField: passwordField, confirmPassField: confirmPassField)
Не го рабирам

2022-03-10 19:39 UTC, StelianRBG commented on MarkMe/MarkMe/Model/AlertError.swift
> +    case facebook = "Facebook Error"
Оправено

2022-03-10 19:40 UTC, StelianRBG commented on MarkMe/MarkMe/Model/AlertError.swift
> +}
Оправено

2022-03-20 14:25 UTC, Lubakis approved these changes
Добра работа

2022-03-20 15:02 UTC, merged