Feature mark info
StelianRBG/ELSYS-GIS-iOS pull request #6
Opened 2022-03-17 20:04 UTC by StelianRBG

2022-03-21 15:06 UTC, Lubakis requested changes

2022-03-21 15:06 UTC, Lubakis commented on MarkMe/MarkMe/Model/Mark.swift
> +    var likes = [String]()
Защо е масив от текст?

2022-03-21 15:06 UTC, Lubakis commented on MarkMe/MarkMe/Model/Mark.swift
> +    var solved = [String]()
Защо е масив от текст? Не е ли достатъчно да е Bool?

2022-03-21 15:06 UTC, Lubakis commented on MarkMe/MarkMe/Screens/ShowMark/ShowMarkViewModel.swift
> +    func setImage(imageView: UIImageView, imgPath: String) {
Това не е нужно да е тук. Не трябва да имаш референция към UIView наследници

2022-03-21 19:27 UTC, StelianRBG commented on MarkMe/MarkMe/Model/Mark.swift
> +    var likes = [String]()
Защото исакм да пазя кои потребител и са го харесали, за да не го харесат отново.

2022-03-21 19:27 UTC, StelianRBG commented on MarkMe/MarkMe/Model/Mark.swift
> +    var solved = [String]()
Защото исакм да пазя кои потребител и са го харесали, за да не го харесат отново.

2022-03-21 19:40 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/ShowMark/ShowMarkViewModel.swift
> +    func setImage(imageView: UIImageView, imgPath: String) {
Оправено

2022-03-22 14:23 UTC, Lubakis approved these changes

2022-03-22 14:26 UTC, merged