Feature mark list
StelianRBG/ELSYS-GIS-iOS pull request #7
Opened 2022-03-21 19:25 UTC by StelianRBG

2022-03-22 14:39 UTC, Lubakis requested changes

2022-03-22 14:39 UTC, Lubakis commented on MarkMe/MarkMe/Screens/MarkList/CustomTableCell/CustomTableViewCell.swift
> +    override func awakeFromNib() {
Това не ти трябва щом не правиш нищо в него

2022-03-22 14:39 UTC, Lubakis commented on MarkMe/MarkMe/Screens/MarkList/CustomTableCell/CustomTableViewCell.swift
> +    @IBAction func pencilDidTap() {
Тази функция е празна

2022-03-22 14:39 UTC, Lubakis commented on MarkMe/MarkMe/Screens/MarkList/MarkListViewController.swift
> +    @IBOutlet private var table: UITableView!
Обикновено кръщаме с View накрая или вида на компонента (Label, TextField и.т.н.)

2022-03-22 14:39 UTC, Lubakis commented on MarkMe/MarkMe/Screens/MarkList/MarkListViewController.swift
> +        if filterData.isEmpty {
Може би tableView.isHidden = filterData.isEmpty?

2022-03-22 14:39 UTC, Lubakis commented on MarkMe/MarkMe/Screens/MarkList/MarkListViewModel.swift
> +    var creatorRef: DocumentReference!
Защо е force unwrapped?

2022-03-22 14:39 UTC, Lubakis commented on MarkMe/MarkMe/Screens/MarkList/MarkListViewModel.swift
> +            self?.marks = documents.compactMap { (document) -> Mark? in
Това може да се напише и с много по-кратка конструкция от вида:

documents.compactMap { try? $0.data(as: Mark.self) }

2022-03-22 14:39 UTC, Lubakis commented on MarkMe/MarkMe/Screens/MarkList/MarkListViewModel.swift
> +            guard querySnapshot?.documents.isEmpty == false, let documents = querySnapshot?.documents else {
Тук е по-добре да направиш следното:

```
guard let documents = querySnapshot?.documents,
          !documents.isEmpty else {
```

2022-03-22 14:39 UTC, Lubakis commented on MarkMe/MarkMe/Screens/MarkList/MarkListViewModel.swift
> +            self?.delegate?.reloadTable()
Дори да има грешка пак презареждаш таблицата?

2022-03-22 14:39 UTC, Lubakis commented on MarkMe/MarkMe/Screens/MarkList/MarkListViewModel.swift
> +    var delegate: CustomTableDelegate?
Ако това е делегат, който ползваш в клетките и тук явно не е CustomTableDelegate, а е по-скоро нещо друго като MarkActionsDelegate

2022-03-22 14:44 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/MarkList/CustomTableCell/CustomTableViewCell.swift
> +    @IBAction func pencilDidTap() {
Да защото тя е за следващия PR

2022-03-22 15:43 UTC, stodorichkov commented on MarkMe/MarkMe/Screens/MarkList/CustomTableCell/CustomTableViewCell.swift
> +    override func awakeFromNib() {
Оправено

2022-03-22 15:45 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/MarkList/MarkListViewController.swift
> +    @IBOutlet private var table: UITableView!
Оправено

2022-03-22 15:46 UTC, stodorichkov commented on MarkMe/MarkMe/Screens/MarkList/MarkListViewController.swift
> +        if filterData.isEmpty {
Оправено

2022-03-22 15:49 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/MarkList/MarkListViewModel.swift
> +            self?.marks = documents.compactMap { (document) -> Mark? in
Оправено

2022-03-22 15:49 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/MarkList/MarkListViewModel.swift
> +    var creatorRef: DocumentReference!
Оправено

2022-03-22 15:50 UTC, stodorichkov commented on MarkMe/MarkMe/Screens/MarkList/MarkListViewModel.swift
> +            guard querySnapshot?.documents.isEmpty == false, let documents = querySnapshot?.documents else {
Оправено

2022-03-22 15:52 UTC, stodorichkov commented on MarkMe/MarkMe/Screens/MarkList/MarkListViewModel.swift
> +            self?.delegate?.reloadTable()
Оправено

2022-03-22 16:00 UTC, StelianRBG commented on MarkMe/MarkMe/Screens/MarkList/MarkListViewModel.swift
> +    var delegate: CustomTableDelegate?
Оправено

2022-03-24 08:35 UTC, Lubakis commented on MarkMe/MarkMe/Screens/MarkList/MarkListViewController.swift
> +        tableView.dataSource = self
По принцип да знаеш, че има по-актуален начин за това Diffable Data Source. Може да прочетеш, но няма време според мен да обръщаш освен ако не го направим след като предадедш.

2022-03-24 08:35 UTC, Lubakis commented on MarkMe/MarkMe/Screens/MarkList/MarkListViewController.swift
> +        tableView.register(CustomTableViewCell.nib(), forCellReuseIdentifier: CustomTableViewCell.identifier)
Тук също има по-модерен вариант за iOS 14+ Content Configuration. Можеш да прочетеш, но ще го правим след като предадеш ако искаш

2022-03-24 08:36 UTC, Lubakis approved these changes
По-добре са нещата. Оставил съм няколко коментара. Виж си ги, но можеш да мърджвааш

2022-03-24 10:10 UTC, merged